### ISSUE TITLE
THREEx.RendererStats  Wrong Vertex Count?

### ISSUE THREAD

**Issue by schoening** [jeromeetienne/threex#59]
I find this odd.. 
The Renderstats on this http://hastebin.com/wuyuqapeka.xml are giving me these results:

WebGLRenderer
== Memory ==
Programs: 1
Geometries: 1
Textures: 0
== Render ==
Calls: 1
Vertices: 2904
Faces: 968
Points: 0

However this line:
console.log(geometry.vertices.length);

Counts only 507 Verticies in the Geometry.
Any idea?

**Comment by J-Zeitler** [comment]
I ran into this issue using a `BufferGeometry`. I add 3 different attributes for it:

```javascript
  geo.addAttribute('position', new THREE.BufferAttribute(positions, 3));
  geo.addAttribute('index', new THREE.BufferAttribute(indices, 1));
  geo.addAttribute('uv', new THREE.BufferAttribute(uvs, 2));
```

It seems like the renderer reports the length of the `indices` array as the vertex count. This naturally results in more "vertices" than the actual vertex count because the same vertex appears multiple times in the index array.

**An example**:

For a plane geometry with 4x4=16 vertices, each "vertex quad" will contribute 2 triangles/faces to the resulting geometry. Each triangle will have 3 entries in the index buffer.

```
+------+------+------+
|      |      |      |
+------+------+------+
|      |      |      |
+------+------+------+
|      |      |      |
+------+------+------+
=> 9 quads * 2x3 indices = 54 index buffer entries (18 faces)
```

Print on my buffers:
![buffer-length](https://cloud.githubusercontent.com/assets/1719257/6798199/f32d6c50-d20a-11e4-85fd-69190839053e.png)

Renderstats shows this:
![renderstats](https://cloud.githubusercontent.com/assets/1719257/6798200/f884b762-d20a-11e4-9ed5-30fc890c0a2d.png)
